# Generated by Django 5.0.6 on 2024-06-26 06:16

import autoslug.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(default='', max_length=255, verbose_name='titleRu')),
                ('title_kz', models.CharField(default='', max_length=255, verbose_name='titleKz')),
                ('title_en', models.CharField(default='', max_length=255, verbose_name='titleEn')),
                ('slug', autoslug.fields.AutoSlugField(default=None, editable=False, populate_from='title_ru', unique=True)),
                ('content_ru', models.TextField(blank=True, default='', null=True, verbose_name='Содержание (рус)')),
                ('content_kz', models.TextField(blank=True, default='', null=True, verbose_name='Содержание (каз)')),
                ('content_eng', models.TextField(blank=True, default='', null=True, verbose_name='Содержание (анг)')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('main_image', models.ImageField(blank=True, default='', null=True, upload_to='news_images/', verbose_name='Основное изображение')),
                ('contact_info', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Контактная информация')),
                ('is_archive', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ['-pub_date'],
            },
        ),
        migrations.CreateModel(
            name='NewsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default=None, upload_to='news_images/', verbose_name='Дополнительное изображение')),
                ('news', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='additional_images', to='news_app.news')),
            ],
            options={
                'verbose_name': 'Дополнительное изображение',
                'verbose_name_plural': 'Дополнительные изображения',
            },
        ),
    ]
