# Generated by Django 5.0.6 on 2024-08-21 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0002_alter_news_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='content_eng',
            field=models.TextField(default='', verbose_name='Содержание (анг)'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content_kz',
            field=models.TextField(default='', verbose_name='Содержание (каз)'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content_ru',
            field=models.TextField(default='', verbose_name='Содержание (рус)'),
        ),
        migrations.AlterField(
            model_name='news',
            name='main_image',
            field=models.ImageField(default='', upload_to='news_images/', verbose_name='Основное изображение'),
        ),
    ]
