# Generated by Django 5.0.6 on 2024-08-27 15:42

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0003_alter_news_content_eng_alter_news_content_kz_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='title_ru', unique=True),
        ),
    ]
