# Generated by Django 5.0.6 on 2024-08-28 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0005_alter_news_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='content_eng',
            field=models.TextField(default='', verbose_name='Содержание en'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content_kz',
            field=models.TextField(default='', verbose_name='Содержание kz'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content_ru',
            field=models.TextField(default='', verbose_name='Содержание ru'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title_en',
            field=models.CharField(default='', max_length=255, verbose_name='Заголовок En'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title_kz',
            field=models.CharField(default='', max_length=255, verbose_name='Заголовок Kz'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title_ru',
            field=models.CharField(default='', max_length=255, verbose_name='Заголовок Ru'),
        ),
    ]
