# Generated by Django 5.0.6 on 2024-06-23 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0007_alter_news_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='content',
        ),
        migrations.AddField(
            model_name='news',
            name='content_eng',
            field=models.TextField(blank=True, null=True, verbose_name='Содержание (анг)'),
        ),
        migrations.AddField(
            model_name='news',
            name='content_kz',
            field=models.TextField(blank=True, null=True, verbose_name='Содержание (каз)'),
        ),
        migrations.AddField(
            model_name='news',
            name='content_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Содержание (рус)'),
        ),
    ]
