# Generated by Django 5.0.6 on 2024-06-24 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0008_remove_news_content_news_content_eng_news_content_kz_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='is_archive',
            field=models.BooleanField(default=False),
        ),
    ]
