# Generated by Django 5.0.6 on 2024-06-25 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_event_ru', models.CharField(max_length=100, verbose_name='Заголовок на русском языке')),
                ('title_event_kz', models.CharField(max_length=100, verbose_name='Заголовок на казахском языке')),
                ('title_event_en', models.CharField(max_length=100, verbose_name='Заголовок на английском языке')),
                ('content_event_ru', models.TextField(verbose_name='Контент на русском языке')),
                ('content_event_kz', models.TextField(verbose_name='Контент на казахском языке')),
                ('content_event_en', models.TextField(verbose_name='Контент на английском языке')),
                ('location', models.CharField(max_length=200, verbose_name='Место проведения')),
                ('date', models.DateField(verbose_name='Дата проведения')),
                ('start_time', models.TimeField(verbose_name='Время начала')),
                ('end_time', models.TimeField(verbose_name='Время окончания')),
            ],
            options={
                'verbose_name': 'Событие',
                'verbose_name_plural': 'События',
            },
        ),
    ]
