# Generated by Django 5.0.6 on 2024-06-25 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='event_images/', verbose_name='Изображение события'),
        ),
    ]
