# Generated by Django 5.0.6 on 2024-08-27 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events_app', '0002_event_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Событие', 'verbose_name_plural': 'Все События'},
        ),
    ]
