# Generated by Django 5.0.6 on 2024-08-28 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events_app', '0003_alter_event_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='date',
            new_name='date_change',
        ),
    ]
