# Generated by Django 5.0.6 on 2024-08-18 04:38

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_book_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newbook',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, default=1, editable=False, populate_from='title', unique=True),
            preserve_default=False,
        ),
    ]
