# Generated by Django 5.0.6 on 2024-08-27 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_book_app', '0003_remove_newbook_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newbook',
            options={'verbose_name': 'Новая Книга', 'verbose_name_plural': 'Новые Книги'},
        ),
    ]
