from app.services.vector_search_service.esimder_vector_handler import EsimderVectorHandler
from .base_vector_search import BaseVectorSearchRouter

router = BaseVectorSearchRouter(EsimderVectorHandler()).router