from app.services.vector_search_service.general_vector_handler import GeneralVectorHandler
from .base_vector_search import BaseVectorSearchRouter

router = BaseVectorSearchRouter(GeneralVectorHandler()).router