# Generated by Django 5.0.6 on 2024-06-25 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_title_ru', models.CharField(max_length=100, verbose_name='Название на русском')),
                ('course_title_kz', models.CharField(max_length=100, verbose_name='Название на казахском')),
                ('course_title_en', models.CharField(max_length=100, verbose_name='Название на английском')),
                ('image', models.ImageField(blank=True, null=True, upload_to='course_images/', verbose_name='Изображение курса')),
                ('start_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
                'ordering': ['-start_date'],
            },
        ),
    ]
