# Generated by Django 5.0.6 on 2024-09-05 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0003_alter_course_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='start_date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата начала'),
        ),
    ]
