# Generated by Django 5.0.6 on 2024-07-16 17:16

import app.time_app.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TimeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_change', models.DateField(default=app.time_app.models.get_future_date, verbose_name='Дата')),
                ('time_start', models.TimeField(default=datetime.time(9, 0), verbose_name='Время начало работы библиотеки')),
                ('time_end', models.TimeField(default=datetime.time(19, 0), verbose_name='Время окончания работы библиотеки')),
            ],
        ),
    ]
