# Generated by Django 5.0.6 on 2024-07-16 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('time_app', '0003_delete_specialday_remove_timemodel_time_end_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timemodel',
            options={'verbose_name': 'Изменение Времени', 'verbose_name_plural': 'Список Изменений Времени'},
        ),
    ]
