# Generated by Django 5.0.6 on 2024-08-27 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('time_app', '0005_alter_timemodel_custom_time_start'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timemodel',
            options={'ordering': ('date_change',), 'verbose_name': 'Изменение Времени', 'verbose_name_plural': 'Список Изменений Времени'},
        ),
    ]
